### ISSUE TITLE
Support for relative paths with `chan.id`

### ISSUE THREAD

**Issue by Fopstronaut** [accumulator/charge-lnd#119]
Can we use relative paths in the config file for peerlists instead of specifying the full path every time?

**Comment by feelancer21** [comment]
There is a little hack. You can write `chan.id=file:\\mychannel.list`, but it only works if you run charge-lnd in the folder of the config, because the paths are interpreted relative to the working dir.

If you like to run charge-lnd via cron, then you can change the directory before:
`cd /path/to/config/folder; charge-lnd -c file.config`
