### ISSUE TITLE
Support for multi-arch (so that we can run it on Umbrel)

### ISSUE THREAD

**Issue by entreprenewer** [accumulator/charge-lnd#35]
With some assistance from @Jorijn, I am working on creating an install guide for Umbrel users, allowing them to create a separate docker with charge-lnd (Because Umbrel is all dockerized, and I want to avoid it uninstalling and wiping out the changes every time users update). 

I am trying to run this command:

`docker run --platform linux/arm64/v8 --rm -it --network=umbrel_main_network   -e GRPC_LOCATION=lnd:10009   -e LND_DIR=/data/.lnd   -e CONFIG_LOCATION=/app/charge.config   -v $(pwd)/umbrel/lnd:/data/.lnd   -v $(pwd)/umbrel/apps/charge-lnd/charge.conf:/app/charge.config    docker.pkg.github.com/accumulator/charge-lnd/charge-lnd:latest
`

However, I get this response:

```
docker: Error response from daemon: image with reference docker.pkg.github.com/accumulator/charge-lnd/charge-lnd:latest was found but does not match the specified platform: wanted linux/arm64v8, actual: linux/amd64.
See 'docker run --help'.
```
This is particularly confusing, because the Raspberry Pi 4B is 100% certainly ARM v8.

I cannot figure out how to get around this and get it to recognize the right platform in order to install, so I'm completely stuck.

Thanks for your help, all!

**Comment by thaJeztah** [comment]
Is `docker.pkg.github.com/accumulator/charge-lnd/charge-lnd:latest` a multi-arch image? The error indicates that the image does not provide an arm variant, and because the `docker run` explicitly specifies  a `--platform` it will refuse to use a different architecture;

What does `docker manifest inspect docker.pkg.github.com/accumulator/charge-lnd/charge-lnd:latest` show?

**Comment by entreprenewer** [comment]
Thanks for the fast reply!!! Wow. 

It shows:

`failed to configure transport: unsupported registry version`

I did try running it without the --platform command, but it wouldn't work at all, either.

**Comment by thaJeztah** [comment]
Ah, yes, forgot that `docker.pkg.github.com` is a non-compliant registry, and only partially implements the OCI Distribution Spec. (I think it's marked as "deprecated" in favor of GitHub's `ghcr.io` registry; https://github.com/moby/moby/issues/41687)


> I did try running it without the --platform command, but it wouldn't work at all, either.

Yes, all of the above seems to indicate that image only supports x86 / amd64. On Docker Desktop for Mac you _may_ be able to run such an image, because it has ("best effort") support for non-matching architectures (using qemu), but if you try to run it on a raspberry Pi, that won't work.

The only solution for that would be if the image was provided as a multi-arch image (and would include variants for both ARM and x86)

**Comment by entreprenewer** [comment]
Ah. Ok. Thanks. Very strange because they do note that it works in Raspiblitz which also uses a raspberry pi 4B and should have the same architecture. In any case… I guess I’ll have to wait for someone to update this code so it can work on umbrel.

**Comment by entreprenewer** [comment]
I found this article
https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

I can try to follow directions and make a multi arch… but I don’t even know how to use docker or code… so who knows how I’ll fare. @accumulator is this something you can take on or should I try?

**Comment by Jorijn** [comment]
It looks like @accumulator already updated the pipeline to include multi-architecture builds, but it's pushing to Docker Hub. You should be able to use `accumulator/charge-lnd`. For Raspberry Pi: https://hub.docker.com/layers/accumulator/charge-lnd/latest/images/sha256-0cef03e2e0fe6d1387f663f26a87c9b27e4f428d87c5693b81baa129fb0ed4d0?context=explore

**Comment by accumulator** [comment]
Wow, cool to see this got resolved so quickly :) 
Luckily I added arm builds a few days ago already. I'll remove the confusing github docker builds

**Comment by thaJeztah** [comment]
That's good news, thanks!

**Comment by entreprenewer** [comment]
Ok perhaps I’ll try again. I was getting stuck anyways even once I discovered the arm build.
